config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # "components#food_categories"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # We do not have a user dashboard because the saved_recipes and saved_chefs dashboard would be the index for saved_recipes and saved_chefs (similar to booking dashboard in rent_my_shoes)
  resources :food_categories, only: %i[index] do
    resources :food_items, only: %i[index]
  end

  resources :recipes, only: %i[index show], shallow: true do
    resources :missing_items, only: %i[create new]
    resources :reviews, only: %i[index show create new]
    resources :recipe_steps, only: %i[index show]
    resources :saved_recipes, only: %i[create new destroy]
  end

  get "fooditems", to: "food_categories#search", as: "food_category_items"
  resources :shopping_carts, only: %i[index show]
  resources :saved_chefs, only: %i[index create new destroy]
  resources :saved_recipes, only: %i[index]
  get "recipes/:id/missing_items", to: "recipes#missing_items", as: "missing_items"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
  has_many :recipes
  has_many :saved_chefs
end

app/models/food_category.rb
class FoodCategory < ApplicationRecord
  has_many :food_items
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :food_category
  has_many :recipe_food_item
  has_many :missing_items
  has_one_attached :food_image

  include PgSearch::Model
  pg_search_scope :search_by_name_and_food_category_id,
    against: [ :name ],
    using: {
    tsearch: { prefix: true }
    }
  include PgSearch::Model
  multisearchable against: [:name, :food_category_id]
end

app/models/missing_item.rb
class MissingItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :shopping_cart
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  has_many :saved_recipes
  has_many :recipe_food_item
  has_many :reviews
  has_many :recipe_steps
  has_one_attached :photo
end

app/models/recipe_food_item.rb
class RecipeFoodItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :recipe
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe
  belongs_to :user


  def review_user_name
    User.find(user_id).first_name
  end

end

app/models/saved_chef.rb
class SavedChef < ApplicationRecord
  belongs_to :user
  belongs_to :chef
end

app/models/saved_recipe.rb
class SavedRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :missing_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :shopping_cart
  has_many :saved_chefs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :saved_recipes
  has_many :reviews
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def index
    @food_items = FoodItem.where(food_category_id: params[:food_category_id]).first(21)
  end

  def search
    if params[:query].present?
      @food_items = FoodItem.search_by_name_and_food_category_id(params[:query])
    else
      @food_items = FoodItem.all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    # raise
    # selected_products = params[:food_item][:your_selection].drop(1)
    # create_cookies(products: selected_products)
    # recipe_food_items = RecipeFoodItem.group(:recipe_id).where(food_item_id: selected_products).count
    all_final_selected_products_array = $all_final_selected_products.flatten
    recipe_food_items = RecipeFoodItem.group(:recipe_id).where(food_item_id: all_final_selected_products_array).count
    recipes_with_selected_products = recipe_food_items.select { |_recipe_id, count| count > 1 }
    recipes_with_selected_products = recipes_with_selected_products.keys
    @recipes = Recipe.find(recipes_with_selected_products)
    # self.show
  end

  def show
    @recipe = Recipe.find(params[:id])
    all_ingredients = RecipeFoodItem.where(recipe_id: @recipe.id)
    all_ingredients_array = []
    all_ingredients.each do |ingredient|
      all_ingredients_array << ingredient.food_item_id
    end
    @selected_ingredients = $all_final_selected_products.flatten.map(&:to_i)
    @missing_ingredients = all_ingredients_array - @selected_ingredients

    @saved_recipe = SavedRecipe.where(user: current_user, recipe: @recipe).first
    @array_ratings = []

    get_reviews

    @clean_array = @array_ratings.reject do |rating|
      rating == nil
    end
    # @average = @clean_array.sum / @clean_array.length
    @average = @clean_array.empty? ? 0 : (@clean_array.sum.to_f / @clean_array.length).round(1)
  end

  private

  def get_reviews
    @recipe.reviews.each do |review|
      @array_ratings << review.rating
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @review = Review.new(review_params)
    @review.recipe = Recipe.find(params[:recipe_id])
    @review.user_id = current_user.id
    @recipe = @review.recipe
    if @review.save
      redirect_to  recipe_path(params["recipe_id"].to_i)
    else
      render :new, status: :bad_request
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :user_id, :recipe_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Nothing needs to go in here
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatsCooking</title>
      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="mobile-web-app-capable" content="yes">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Pacifico&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600&display=swap');
  </style>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
        <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://ga.jspm.io/npm:star-rating.js@4.3.0/dist/star-rating.css">
  </head>

  <body>
      <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
     <div class="main-container">
    <%= yield %>


    </div>
    <%= render "shared/bottom_nav" %>


  </body>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-element-bundle.min.js"></script>
</html>

app/views/shared/_bottom_nav.html.erb
<div class="bottom-nav flex-end">
<div class="bottom-nav-item">
<%= icon("fa-solid fa-house" , style:"color: $primary-color;") %>
<%=link_to "", root_path, class: 'btn-link'%>
</div>

<div class="bottom-nav-item">
<%= icon("fa-solid fa-magnifying-glass" , style:"color: $primary-color;") %>
<%=link_to "", food_categories_path, class: 'btn-link'%>
</div>

<div class="bottom-nav-item">
<%= icon("fa-solid fa-heart" , style:"color: $primary-color;") %>
<%=link_to "", saved_recipes_path, class: 'btn-link'%>
</div>

<% unless current_user.nil? %>

  <% if current_user.shopping_cart_id.present? || ShoppingCart.where(user_id: current_user.id).last.id%>
    <div class="bottom-nav-item">
      <%= icon("fa-solid fa-shopping-cart" , style:"color: $primary-color;") %>
      <%=link_to "", shopping_cart_path(ShoppingCart.where(user_id: current_user.id).last.id), class: 'btn-link' %>
    </div>
  <% else %>
    <div class="bottom-nav-item">
    </div>
  <% end %>

<% end %>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon">
  <div class="container-fluid">
      <ul class="navbar-nav ms-0 d-flex justify-content-between" style="flex-grow: 1;">
          <div class="logo">
           <p style="font-family:'Pacifico', cursive;">What's Cooking?</p>
            <%= icon("fa-solid fa-lemon fa-xl", style:"color: $primary-color; border:1px solid black;") %>
          </div>
          <div>
            <% if user_signed_in? %>
              <div>
                <li class="nav-item dropdown">
                <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag("avatar.png", class: "avatar", alt: "dropdown menu") %>
                </a>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <%= link_to "My Profile", "#", class: "dropdown-item" %>
                    <%= link_to "Saved Recipes", "#", class: "dropdown-item" %>
                    <%= link_to "Saved Chefs", "#", class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                  </div>
                </li>
              </div>
            <% else %>
             <div>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
              </div>
            <% end %>
          </div>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search">
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: food_category_items_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type here"
        %>
      <%= submit_tag "Search", name: "", class:"secondary-btn-search"%>
    <% end %>
  </div>
</div>
</div>