config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # "components#food_categories"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # We do not have a user dashboard because the saved_recipes and saved_chefs dashboard would be the index for saved_recipes and saved_chefs (similar to booking dashboard in rent_my_shoes)
  resources :food_categories, only: %i[index] do
    resources :food_items, only: %i[index]
  end

  resources :recipes, only: %i[index show], shallow: true do
    resources :missing_items, only: %i[create new]
    resources :reviews, only: %i[index show create new]
    resources :recipe_steps, only: %i[index show]
    resources :saved_recipes, only: %i[create new destroy]
  end

  get "fooditems", to: "food_categories#search", as: "food_category_items"
  resources :shopping_carts, only: %i[index show]
  resources :saved_chefs, only: %i[index create new destroy]
  resources :saved_recipes, only: %i[index]
  get "recipes/:id/missing_items", to: "recipes#missing_items", as: "missing_items"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
  has_many :recipes
  has_many :saved_chefs
end

app/models/food_category.rb
class FoodCategory < ApplicationRecord
  has_many :food_items
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :food_category
  has_many :recipe_food_item
  has_many :missing_items
  has_one_attached :food_image

  include PgSearch::Model
  pg_search_scope :search_by_name_and_food_category_id,
    against: [ :name ],
    using: {
    tsearch: { prefix: true }
    }
  include PgSearch::Model
  multisearchable against: [:name, :food_category_id]
end

app/models/missing_item.rb
class MissingItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :shopping_cart
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  has_many :saved_recipes
  has_many :recipe_food_item
  has_many :reviews
  has_many :recipe_steps
  has_one_attached :photo
end

app/models/recipe_food_item.rb
class RecipeFoodItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :recipe
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe
  belongs_to :user


  def review_user_name
    User.find(user_id).first_name
  end

end

app/models/saved_chef.rb
class SavedChef < ApplicationRecord
  belongs_to :user
  belongs_to :chef
end

app/models/saved_recipe.rb
class SavedRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :missing_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :shopping_cart
  has_many :saved_chefs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :saved_recipes
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_shopping_cart

  def current_shopping_cart
    current_user&.shopping_cart_id
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def index
    @food_items = FoodItem.where(food_category_id: params[:food_category_id]).first(21)
  end

  def search
    if params[:query].present?
      @food_items = FoodItem.search_by_name_and_food_category_id(params[:query])
    else
      @food_items = FoodItem.all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    # raise
    # selected_products = params[:food_item][:your_selection].drop(1)
    # create_cookies(products: selected_products)
    # recipe_food_items = RecipeFoodItem.group(:recipe_id).where(food_item_id: selected_products).count
    all_final_selected_products_array = $all_final_selected_products.flatten
    recipe_food_items = RecipeFoodItem.group(:recipe_id).where(food_item_id: all_final_selected_products_array).count
    recipes_with_selected_products = recipe_food_items.select { |_recipe_id, count| count > 1 }
    recipes_with_selected_products = recipes_with_selected_products.keys
    @recipes = Recipe.find(recipes_with_selected_products)
    # self.show
  end

  def show
    @recipe = Recipe.find(params[:id])
    all_ingredients = RecipeFoodItem.where(recipe_id: @recipe.id)
    all_ingredients_array = []
    all_ingredients.each do |ingredient|
      all_ingredients_array << ingredient.food_item_id
    end
    @selected_ingredients = $all_final_selected_products.flatten.map(&:to_i)
    @missing_ingredients = all_ingredients_array - @selected_ingredients

    @saved_recipe = SavedRecipe.where(user: current_user, recipe: @recipe).first
    @array_ratings = []

    get_reviews

    @clean_array = @array_ratings.reject do |rating|
      rating == nil
    end
    # @average = @clean_array.sum / @clean_array.length
    @average = @clean_array.empty? ? 0 : (@clean_array.sum.to_f / @clean_array.length).round(1)
  end

  private

  def get_reviews
    @recipe.reviews.each do |review|
      @array_ratings << review.rating
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @review = Review.new(review_params)
    @review.recipe = Recipe.find(params[:recipe_id])
    @review.user_id = current_user.id
    @recipe = @review.recipe
    if @review.save
      redirect_to  recipe_path(params["recipe_id"].to_i)
    else
      render :new, status: :bad_request
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :user_id, :recipe_id)
  end
end

app/controllers/saved_chefs_controller.rb
class SavedChefsController < ApplicationController
  def index
    @saved_chefs = SavedChefs.all
  end

  def new
    @saved_chef = SavedChef.new
  end

  def create
    @saved_chef = SavedChef.new(saved_chef_params)
    @saved_chef.user = current.user
    @saved_chef.chef = Chef.find(params[:id])
    @saved_chef.save
  end

  def delete
    @saved_chef = SavedChef.find(params[id])
    @saved_chef.destroy
    redirect_to saved_chefs_path
  end

  private

  def saved_chef_params
    params.require(saved_chef).permit(:user_id, :chef_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Nothing needs to go in here
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_items/index.html.erb
<div class = 'food-item-page'>
  <h1>Find Today's Recipe</h1>
  <h2>Choose available ingredients</h2>

  <%= simple_form_for :food_item, url:  food_categories_path, method: :get do |f| %>
  <% food_array = @food_items.map do |food| food.name end %>

  <%= f.input :your_selection,
              as: :check_boxes,
              multiple: true,
              collection_wrapper_tag: 'div',
              collection_wrapper_class: 'category-wrapper',
              item_wrapper_class: 'category-item',
              input_html: {multiple:true, class: 'category-selector'},
              collection: @food_items.map {|food|[food.name, food.id, style:"background-image:url(#{image_path "#{food.name.downcase}.jpg"})"]} %>
  <%= f.submit "Done", class: "primary-btn", style:"border: none"%>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div class="recipe-page">
<h1>Choose your recipe</h1>
<h2> We have found  <%= @recipes.count%> recipes</h2>

  <% @recipes.each do |recipe| %>
  <div class="recipe-card">
      <div class="recipe-card-img">
      <% if recipe.id == 1 %>
      <%= image_tag("recipe_imgs/recipe1cover.jpg")%>
      <% elsif recipe.id == 2 %>
      <%= image_tag("recipe_imgs/recipe2cover.jpg")%>
      <% elsif recipe.id == 3 %>
      <%= image_tag("recipe_imgs/recipe3cover.jpg")%>
      <% elsif recipe.id == 4 %>
      <%= image_tag("recipe_imgs/recipe4coverr.jpg")%>
        <% elsif recipe.id == 5 %>
      <%= image_tag("recipe_imgs/recipe5cover.jpg")%>
      <% elsif recipe.id == 6 %>
      <%= image_tag("recipe_imgs/recipe6cover.jpg")%>
      <% elsif recipe.id == 7 %>
      <%= image_tag("recipe_imgs/recipe7cover.jpeg")%>
      <% end %>

  </div>
    <div class="card-contents">
      <h3><%= recipe.name %></h3>
      <p class="chef-name">
           <%= icon("fa-solid fa-circle-check" , style:"color: #cc9191;") %>
           <%= recipe.chef.first_name %>
            <%=recipe.chef.last_name  %>
        </p>
      <% if recipe.reviews %>
      <p>
      <i class="fa-solid fa-star" style="color: #fed401;"></i>
       <% average_rating = recipe.reviews.average(:rating).to_i %>
        <%= average_rating ? average_rating.round(1) : 'No ratings yet' %>
        <span> (<%= recipe.reviews.length %> reviews) </span>
      </p>
      <% else %>
      <p><%= "No reviews yet" %>
      </p>
      <% end %>
      <p class="pill-box"> <%= icon("fa-solid fa-clock", style:"color: #ee7d45;") %> <%= recipe.duration%> min</p>
      <p class="pill-box">
        <%= icon("fa-solid fa-user", style: "color:#ee7d45;")%>
        <% if recipe.portion_size > 1 %>
        <%= recipe.portion_size%> portions
              <% else %>
                      <%= recipe.portion_size%> portion
                      <% end %>
        </p>
    </div>
          <%= link_to '', recipe_path(recipe), class:'recipe-card-link' %>
  </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="recipe-container">
  <h1> <%= @recipe.name %></h1>
  <div class="recipe-img">
    <% if @recipe.id == 1 %>
      <%= image_tag("recipe_imgs/recipe1cover.jpg")%>
    <% elsif @recipe.id == 2 %>
      <%= image_tag("recipe_imgs/recipe2cover.jpg")%>
    <% elsif @recipe.id == 3 %>
      <%= image_tag("recipe_imgs/recipe3cover.jpg")%>
    <% elsif @recipe.id == 4 %>
      <%= image_tag("recipe_imgs/recipe4cover.jpg")%>
    <% elsif @recipe.id == 5 %>
      <%= image_tag("recipe_imgs/recipe5cover.jpg")%>
    <% elsif @recipe.id == 6 %>
      <%= image_tag("recipe_imgs/recipe6cover.jpg")%>
    <% end %>
  </div>

  <div class="recipe-info">
    <p class="pill-box"><%= icon("fa-solid fa-clock", style:"color: #ee7d45;") %> <%= @recipe.duration%> min</p>
      <p class="pill-box">
        <%= icon("fa-solid fa-user", style: "color:#ee7d45;")%>
        <% if @recipe.portion_size > 1 %>
          <%= @recipe.portion_size%> portions
        <% else %>
          <%= @recipe.portion_size%> portion
        <% end %>
        </p>
        <p class="pill-box">
          <%= icon("fa-solid fa-calculator", style:"color: #ee7d45;")%>
          460 calories
        </p>

    <% if @saved_recipe.present? %>
      <div class="icon-wrapper">
        <%= link_to saved_recipe_path(@saved_recipe), data: {turbo_method: :delete }, class: "btn" do %>
          <p><i class="fa-solid fa-heart fa-2x", style="color:#E4425F"></i> Saved</p>
        <% end %>
        </div>
    <% else %>
      <div class="icon-wrapper">
        <%= simple_form_for [@recipe, SavedRecipe.new] do |f| %>
          <%= f.button :button do %>
            <p><i class="fa-regular fa-heart fa-2x" , style="color:#E4425F"></i> Save</p>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="recipe-description">
    <p class="reviews"><i class="fa-solid fa-star" style="color: #fed401;"></i> <%= @average %> (<%= @clean_array.length %> Reviews) </p>
    <h2>Description</h2>
    <p>This wholesome, vegetarian-friendly recipe promises a delightful burst of flavors and a comforting experience that will leave you craving for more.</p>
    <br>

      <h2>Ingredients you have</h2>
      <div class="recipe-ing">
        <% @recipe.recipe_food_item.each do |ing| %>
          <% if @selected_ingredients.include? ing.food_item_id %>
            <div class="missing-item">
            <h2><%= ing.food_item.name %></h2>
            <p><i class="fa-solid fa-check fa-2xl" style="color: #24ae54;" ></i></p>
            </div>
          <% else %>
          <% end %>
        <% end %>
      </div>

    <% if @missing_ingredients.empty? %>
      <h2>Yay! You have all the Ingredients 🎉</h2>
    <% else %>
      <h2>Missing Ingredients</h2>


              <div class="missing-item">

                <%= simple_form_for :food_item, url:  recipe_missing_items_path(@recipe.id), method: :post do |f| %>
                 <%= f.input :your_selection,
                              as: :check_boxes,
                              multiple: true,
                              collection_wrapper_tag: 'div',
                              collection_wrapper_class: 'missing-item-wrapper',
                              item_wrapper_class: 'missing-item-item',
                              input_html: {multiple:true, class: 'missing-item-selector'},
                              collection: @recipe.recipe_food_item.map{|food| if @missing_ingredients.include?(food.food_item_id)
                                                                              [food.food_item.name, food.food_item.id]
                                                                              end}.compact %>
                  <%= f.submit "Add to Cart", class: "cart-btn", style:"border: none"%>

              </div>
          <% end %>

    <% end %>
  </div>


    <%= link_to 'Cooking Steps', recipe_recipe_steps_path(@recipe.id), class:"primary-btn"%>
    <%= link_to 'Back to Recipe List', recipes_path, class:"tertiary-btn"%>
<br>



  <div class="review-section">
<% if @recipe.reviews.empty? %>
<% else %>
  <h1>See what others think </h1>
        <% @recipe.reviews.each do |review| %>
        <div class = 'review-card'>
              <p><i class="fa-solid fa-user" style="color: $primary-color;"> </i>
              </p>
              <% review.rating.to_i.times do |star| %>
                  <i class="fa-solid fa-star" style="color: #fed401;"></i>
              <% end %>
            <p><%= review.comment %></p>
        </div>
        <% end %>
    <% end %>
  </div>
</div>