config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # "components#food_categories"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # We do not have a user dashboard because the saved_recipes and saved_chefs dashboard would be the index for saved_recipes and saved_chefs (similar to booking dashboard in rent_my_shoes)
  resources :food_categories, only: %i[index] do
    resources :food_items, only: %i[index]
  end

  resources :recipes, only: %i[index show], shallow: true do
    resources :missing_items, only: %i[create new]
    resources :reviews, only: %i[index show create new]
    resources :recipe_steps, only: %i[index show]
    resources :saved_recipes, only: %i[create new destroy]
  end

  get "fooditems", to: "food_categories#search", as: "food_category_items"
  resources :shopping_carts, only: %i[index show]
  resources :saved_chefs, only: %i[index create new destroy]
  resources :saved_recipes, only: %i[index]
  get "recipes/:id/missing_items", to: "recipes#missing_items", as: "missing_items"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
  has_many :recipes
  has_many :saved_chefs
end

app/models/food_category.rb
class FoodCategory < ApplicationRecord
  has_many :food_items
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :food_category
  has_many :recipe_food_item
  has_many :missing_items
  has_one_attached :food_image

  include PgSearch::Model
  pg_search_scope :search_by_name_and_food_category_id,
    against: [ :name ],
    using: {
    tsearch: { prefix: true }
    }
  include PgSearch::Model
  multisearchable against: [:name, :food_category_id]
end

app/models/missing_item.rb
class MissingItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :shopping_cart
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  has_many :saved_recipes
  has_many :recipe_food_item
  has_many :reviews
  has_many :recipe_steps
  has_one_attached :photo
end

app/models/recipe_food_item.rb
class RecipeFoodItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :recipe
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe
  belongs_to :user


  def review_user_name
    User.find(user_id).first_name
  end

end

app/models/saved_chef.rb
class SavedChef < ApplicationRecord
  belongs_to :user
  belongs_to :chef
end

app/models/saved_recipe.rb
class SavedRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :missing_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :shopping_cart
  has_many :saved_chefs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :saved_recipes
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_shopping_cart

  def current_shopping_cart
    current_user&.shopping_cart_id
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/food_categories_controller.rb
class FoodCategoriesController < ApplicationController
  def index
    if params[:food_item].present?

      @food_categories = FoodCategory.all
      selected_products = params[:food_item][:your_selection].drop(1)
      session[:final_selected_products] ||= []
      session[:final_selected_products] << selected_products
      $all_final_selected_products = session[:final_selected_products]
    else
      @food_categories = FoodCategory.all
    end
  end

  def search
    if params[:query].present?
      @food_items = FoodItem.search_by_name_and_food_category_id(params[:query])
    else
      @food_items = FoodItem.all
    end
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def index
    @food_items = FoodItem.where(food_category_id: params[:food_category_id]).first(21)
  end

  def search
    if params[:query].present?
      @food_items = FoodItem.search_by_name_and_food_category_id(params[:query])
    else
      @food_items = FoodItem.all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    # raise
    # selected_products = params[:food_item][:your_selection].drop(1)
    # create_cookies(products: selected_products)
    # recipe_food_items = RecipeFoodItem.group(:recipe_id).where(food_item_id: selected_products).count
    all_final_selected_products_array = $all_final_selected_products.flatten
    recipe_food_items = RecipeFoodItem.group(:recipe_id).where(food_item_id: all_final_selected_products_array).count
    recipes_with_selected_products = recipe_food_items.select { |_recipe_id, count| count > 1 }
    recipes_with_selected_products = recipes_with_selected_products.keys
    @recipes = Recipe.find(recipes_with_selected_products)
    # self.show
  end

  def show
    @recipe = Recipe.find(params[:id])
    all_ingredients = RecipeFoodItem.where(recipe_id: @recipe.id)
    all_ingredients_array = []
    all_ingredients.each do |ingredient|
      all_ingredients_array << ingredient.food_item_id
    end
    @selected_ingredients = $all_final_selected_products.flatten.map(&:to_i)
    @missing_ingredients = all_ingredients_array - @selected_ingredients

    @saved_recipe = SavedRecipe.where(user: current_user, recipe: @recipe).first
    @array_ratings = []

    get_reviews

    @clean_array = @array_ratings.reject do |rating|
      rating == nil
    end
    # @average = @clean_array.sum / @clean_array.length
    @average = @clean_array.empty? ? 0 : (@clean_array.sum.to_f / @clean_array.length).round(1)
  end

  private

  def get_reviews
    @recipe.reviews.each do |review|
      @array_ratings << review.rating
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @review = Review.new(review_params)
    @review.recipe = Recipe.find(params[:recipe_id])
    @review.user_id = current_user.id
    @recipe = @review.recipe
    if @review.save
      redirect_to  recipe_path(params["recipe_id"].to_i)
    else
      render :new, status: :bad_request
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :user_id, :recipe_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Nothing needs to go in here
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_categories/index.html.erb
<div class = 'food-categories-page'>
  <h1>Find Today's Recipe</h1>
  <h2>Choose available ingredients</h2>
<%= render 'shared/search' %>
  <div class = 'food-categories-wrapper'>
    <%  @food_categories.each do |food_category| %>
      <div class = 'food-category-card'>
          <div class = 'food-category-icon'>
            <% if food_category.name == 'Vegetables' %>
             <%= icon("fa-solid fa-carrot", style:"color: #FFFFFF;") %>

            <% elsif food_category.name == 'Fruits' %>
              <%= icon("fa-solid fa-apple-whole" , style:"color: #FFFFFF;") %>

            <% elsif food_category.name == 'Dairy' %>
              <%= icon("fa-solid fa-cow" , style:"color: #FFFFFF;") %>

            <% elsif food_category.name == 'Meat' %>
              <%= icon("fa-solid fa-drumstick-bite" , style:"color: #FFFFFF;") %>

            <% elsif food_category.name == 'Poultry' %>
              <%= icon("fa-solid fa-egg" , style:"color: #FFFFFF;") %>

            <% elsif food_category.name == 'Seafood' %>
              <%= icon("fa-solid fa-fish" , style:"color: #FFFFFF;") %>

            <% elsif food_category.name == 'Carbs' %>
              <%= icon("fa-solid fa-bread-slice" , style:"color: #FFFFFF;") %>

            <% elsif food_category.name == 'Spices' %>
            <%= icon("fa-solid fa-mortar-pestle" , style:"color: #FFFFFF;") %>

            <% elsif food_category.name == 'Legumes' %>
              <%= icon("fa-solid fa-seedling" , style:"color: #FFFFFF;") %>
            <% else %>
            <% end %>
          </div>
            <div class = 'food-category-name'><%= food_category.name %></div>
            <%= link_to '', food_category_food_items_path(food_category), class: 'card-link'  %>

      </div>
    <% end %>
     <p class="time-btn"> <%= icon("fa-solid fa-clock", style:"color: #ee7d45;") %> 05-15 mins</p>
      <p class="time-btn"> <%= icon("fa-solid fa-clock", style:"color: #ee7d45;") %> 15-30 mins</p>
       <p class="time-btn"> <%= icon("fa-solid fa-clock", style:"color: #ee7d45;") %> 30-45 mins</p>

  </div>
      <%= link_to 'Show me recipes', recipes_path, class: 'primary-btn'%>
</div>

app/views/food_categories/search.html.erb
<div class = 'food-item-page'>
  <h1>Find Today's Recipe</h1>
  <h2>Choose available ingredients</h2>

  <%= simple_form_for :food_item, url:  food_categories_path, method: :get do |f| %>
  <% food_array = @food_items.map do |food| food.name end %>

  <%= f.input :your_selection,
              as: :check_boxes,
              multiple: true,
              collection_wrapper_tag: 'div',
              collection_wrapper_class: 'category-wrapper_search',
              item_wrapper_class: 'category-item_search',
              input_html: {multiple:true, class: 'category-selector_search'},
              collection: @food_items.map {|food|[food.name, food.id, style:"background-image:url(#{image_path "#{food.name.downcase}.jpg"})"]} %>
  <%= f.submit "Done", class: "primary-btn", style:"border: none"%>
  <% end %>
</div>